"""add severity and summary to agent_lifecycle

Revision ID: 02e96df93587
Revises: 009d3e1b949d
Create Date: 2025-12-09 13:26:45.447334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e96df93587'
down_revision: Union[str, Sequence[str], None] = '009d3e1b949d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_lifecycle', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('agent_lifecycle', sa.Column('severity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_lifecycle', 'severity')
    op.drop_column('agent_lifecycle', 'summary')
    # ### end Alembic commands ###
